"""First migration

Revision ID: 1662648a1aa2
Revises:
Create Date: 2024-11-16 22:06:22.221316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1662648a1aa2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "charges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code_section", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "courts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("court_type", sa.String(), nullable=True),
        sa.Column("fips_code", sa.String(), nullable=True),
        sa.Column("fips_code_4", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_number", sa.String(), nullable=False),
        sa.Column("formatted_case_number", sa.String(), nullable=False),
        sa.Column("charge_amended", sa.Boolean(), nullable=True),
        sa.Column("code_section", sa.String(), nullable=True),
        sa.Column("case_type", sa.String(), nullable=True),
        sa.Column("offense_date", sa.Date(), nullable=True),
        sa.Column("arrest_date", sa.Date(), nullable=True),
        sa.Column("is_criminal", sa.Boolean(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("sub_category", sa.String(), nullable=True),
        sa.Column("is_appeal", sa.Boolean(), nullable=True),
        sa.Column("appeal_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("commenced_by", sa.String(), nullable=True),
        sa.Column("court_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["court_id"],
            ["courts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("formatted_case_number"),
    )
    op.create_table(
        "case_charges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_type_code", sa.String(), nullable=True),
        sa.Column("class_code", sa.String(), nullable=True),
        sa.Column("filling_date", sa.Date(), nullable=False),
        sa.Column("is_original", sa.Boolean(), nullable=True),
        sa.Column("is_amended", sa.Boolean(), nullable=True),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("charge_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["charge_id"],
            ["charges.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("case_charges")
    op.drop_table("cases")
    op.drop_table("courts")
    op.drop_table("charges")
    # ### end Alembic commands ###
