import json
import os

dir_path = os.path.dirname(os.path.realpath(__file__))
with open(f"{dir_path}/courts.json") as f:
    courts = json.load(f)

FINAL_COLUMNS = [
    "Case Number",
    "Filed Date",
    "Locality",
    "Name",
    "Status",
    "Defense Attorney",
    "Address",
    "AKA1",
    "AKA2",
    "Gender",
    "Race",
    "DOB",
    "Charge",
    "Code Section",
    "Case Type",
    "Class",
    "Offense Date",
    "Arrest Date",
    "Complainant",
    "Amended Charge",
    "Amended Code",
    "Amended Case Type",
    "Date,Time,Result,Hearing Type,Courtroom,Plea,Continuance Code,,Final Disposition",
    "Sentence Time",
    "Sentence Suspended Time",
    "Probation Type",
    "Probation Time",
    "Probation Starts",
    "Operator License Suspension Time",
    "Restriction Effective Date",
    "Operator License Restriction Codes",
    "Fine",
    "Costs",
    "Fine/Costs Due",
    "Fine/Costs Paid",
    "Fine/Costs Paid Date",
    "VASAP",
    "searchDate",
    "Court",
]


# COURTS = {
#     "001C": "Accomack Circuit Court",
#     "001G": "Accomack General District Court",
#     "": "",
#     "": "",
#     "": "",
#     "": "",
#     "": "",
# }

# codes = [
#     "001C",
#     "001G",
#     "003C",
#     "003G",
#     "510C",
#     "510G",
#     "005C",
#     "005G",
#     "007C",
#     "007G",
#     "009C",
#     "009G",
#     "011C",
#     "011G",
#     "013C",
#     "013G",
#     "015C",
#     "015G",
#     "017C",
#     "017G",
#     "019C",
#     "019G",
#     "021C",
#     "021G",
#     "023C",
#     "023G",
#     "520C",
#     "520G",
#     "025C",
#     "025G",
#     "027C",
#     "027G",
#     "029C",
#     "029G",
#     "530C",
#     "530G",
#     "031C",
#     "031G",
#     "033C",
#     "033G",
#     "035C",
#     "035G",
#     "036C",
#     "036G",
#     "037C",
#     "037G",
#     "540C",
#     "540G",
#     "550C",
#     "550G",
#     "041C",
#     "041G",
#     "043C",
#     "043G",
#     "560C",
#     "570C",
#     "570G",
#     "045C",
#     "045G",
#     "047C",
#     "047G",
#     "049C",
#     "049G",
#     "590C",
#     "590G",
#     "051C",
#     "051G",
#     "053C",
#     "053G",
#     "595G",
#     "057C",
#     "057G",
#     "059C",
#     "600G",
#     "059G",
#     "610G",
#     "061C",
#     "061G",
#     "063C",
#     "063G",
#     "065C",
#     "065G",
#     "067C",
#     "620G",
#     "067G",
#     "069C",
#     "069G",
#     "630C",
#     "630G",
#     "640G",
#     "071C",
#     "071G",
#     "073C",
#     "073G",
#     "075C",
#     "075G",
#     "077C",
#     "077G",
#     "079C",
#     "079G",
#     "081C",
#     "081G",
#     "083C",
#     "083G",
#     "650C",
#     "650G",
#     "085C",
#     "085G",
#     "165G",
#     "087C",
#     "087G",
#     "089C",
#     "089G",
#     "091C",
#     "091G",
#     "670C",
#     "670G",
#     "093C",
#     "093G",
#     "097C",
#     "097G",
#     "099C",
#     "099G",
#     "101C",
#     "101G",
#     "103C",
#     "103G",
#     "105C",
#     "105G",
#     "163G",
#     "107C",
#     "107G",
#     "109C",
#     "109G",
#     "111C",
#     "111G",
#     "680C",
#     "680G",
#     "113C",
#     "113G",
#     "690C",
#     "690G",
#     "115C",
#     "115G",
#     "117C",
#     "117G",
#     "119C",
#     "119G",
#     "121C",
#     "122G",
#     "121G",
#     "125C",
#     "125G",
#     "127C",
#     "127G",
#     "700C",
#     "703G",
#     "701G",
#     "702G",
#     "710C",
#     "710G",
#     "713G",
#     "711G",
#     "712G",
#     "131C",
#     "131G",
#     "133C",
#     "133G",
#     "135C",
#     "135G",
#     "137C",
#     "137G",
#     "139C",
#     "139G",
#     "141C",
#     "141G",
#     "730C",
#     "730G",
#     "143C",
#     "143G",
#     "740C",
#     "740G",
#     "145C",
#     "145G",
#     "147C",
#     "147G",
#     "149C",
#     "149G",
#     "153C",
#     "153G",
#     "155C",
#     "155G",
#     "750C",
#     "750G",
#     "157C",
#     "157G",
#     "760C",
#     "760G",
#     "159C",
#     "159G",
#     "764G",
#     "763G",
#     "762G",
#     "761G",
#     "770C",
#     "770G",
#     "161C",
#     "161G",
#     "163C",
#     "165C",
#     "167C",
#     "167G",
#     "775C",
#     "775G",
#     "169C",
#     "169G",
#     "171C",
#     "171G",
#     "173C",
#     "173G",
#     "175C",
#     "175G",
#     "177C",
#     "177G",
#     "179C",
#     "179G",
#     "790C",
#     "790G",
#     "800C",
#     "800G",
#     "181C",
#     "181G",
#     "183C",
#     "183G",
#     "185C",
#     "185G",
#     "810C",
#     "810G",
#     "187C",
#     "187G",
#     "191C",
#     "191G",
#     "820C",
#     "820G",
#     "193C",
#     "193G",
#     "830C",
#     "830G",
#     "840C",
#     "840G",
#     "195C",
#     "195G",
#     "197C",
#     "197G",
#     "199C",
#     "199G",
# ]

# court_names = [
#     "Accomack Circuit Court",
#     "Accomack General District Court",
#     "Albemarle Circuit Court",
#     "Albemarle General District Court",
#     "Alexandria General District Court",
#     "Alleghany Circuit Court",
#     "Alleghany General District Court",
#     "Amelia Circuit Court",
#     "Amelia General District Court",
#     "Amherst Circuit Court",
#     "Amherst General District Court",
#     "Appomattox Circuit Court",
#     "Appomattox General District Court",
#     "Arlington Circuit Court",
#     "Arlington General District Court",
#     "Augusta Circuit Court",
#     "Augusta General District Court",
#     "Bath Circuit Court",
#     "Bath General District Court",
#     "Bedford Circuit Court",
#     "Bedford General District Court",
#     "Bland Circuit Court",
#     "Bland General District Court",
#     "Botetourt Circuit Court",
#     "Botetourt General District Court",
#     "Bristol Circuit Court",
#     "Bristol General District Court",
#     "Brunswick Circuit Court",
#     "Brunswick General District Court",
#     "Buchanan Circuit Court",
#     "Buchanan General District Court",
#     "Buckingham Circuit Court",
#     "Buckingham General District Court",
#     "Buena Vista Circuit Court",
#     "Buena Vista General District Court",
#     "Campbell Circuit Court",
#     "Campbell General District Court",
#     "Caroline Circuit Court",
#     "Caroline General District Court",
#     "Carroll Circuit Court",
#     "Carroll General District Court",
#     "Charles City Circuit Court",
#     "Charles City General District Court",
#     "Charlotte Circuit Court",
#     "Charlotte General District Court",
#     "Charlottesville Circuit Court",
#     "Charlottesville General District Court",
#     "Chesapeake Circuit Court",
#     "Chesapeake General District Court",
#     "Chesterfield Circuit Court",
#     "Chesterfield General District Court",
#     "Clarke Circuit Court",
#     "Clarke General District Court",
#     "Clifton Forge Circuit Court",
#     "Colonial Heights Circuit Court",
#     "Colonial Heights General District Court",
#     "Craig Circuit Court",
#     "Craig General District Court",
#     "Culpeper Circuit Court",
#     "Culpeper General District Court",
#     "Cumberland Circuit Court",
#     "Cumberland General District Court",
#     "Danville Circuit Court",
#     "Danville General District Court",
#     "Dickenson Circuit Court",
#     "Dickenson General District Court",
#     "Dinwiddie Circuit Court",
#     "Dinwiddie General District Court",
#     "Emporia General District Court",
#     "Essex Circuit Court",
#     "Essex General District Court",
#     "Fairfax City General District Court",
#     "Fairfax County General District Court",
#     "Falls Church General District Court",
#     "Fauquier Circuit Court",
#     "Fauquier General District Court",
#     "Floyd Circuit Court",
#     "Floyd General District Court",
#     "Fluvanna Circuit Court",
#     "Fluvanna General District Court",
#     "Franklin Circuit Court",
#     "Franklin City General District Court",
#     "Franklin County General District Court",
#     "Frederick Circuit Court",
#     "Frederick General District Court",
#     "Fredericksburg Circuit Court",
#     "Fredericksburg General District Court",
#     "Galax General District Court",
#     "Giles Circuit Court",
#     "Giles General District Court",
#     "Gloucester Circuit Court",
#     "Gloucester General District Court",
#     "Goochland Circuit Court",
#     "Goochland General District Court",
#     "Grayson Circuit Court",
#     "Grayson General District Court",
#     "Greene Circuit Court",
#     "Greene General District Court",
#     "Greensville Circuit Court",
#     "Greensville General District Court",
#     "Halifax Circuit Court",
#     "Halifax General District Court",
#     "Hampton Circuit Court",
#     "Hampton General District Court",
#     "Hanover Circuit Court",
#     "Hanover General District Court",
#     "Henrico Circuit Court",
#     "Henrico General District Court",
#     "Henry Circuit Court",
#     "Henry General District Court",
#     "Highland Circuit Court",
#     "Highland General District Court",
#     "Hopewell Circuit Court",
#     "Hopewell General District Court",
#     "Isle of Wight Circuit Court",
#     "Isle of Wight General District Court",
#     "King and Queen Circuit Court",
#     "King and Queen General District Court",
#     "King George Circuit Court",
#     "King George General District Court",
#     "King William Circuit Court",
#     "King William General District Court",
#     "Lancaster Circuit Court",
#     "Lancaster General District Court",
#     "Lee Circuit Court",
#     "Lee General District Court",
#     "Loudoun Circuit Court",
#     "Loudoun General District Court",
#     "Louisa Circuit Court",
#     "Louisa General District Court",
#     "Lunenburg Circuit Court",
#     "Lunenburg General District Court",
#     "Lynchburg Circuit Court",
#     "Lynchburg General District Court",
#     "Madison Circuit Court",
#     "Madison General District Court",
#     "Martinsville Circuit Court",
#     "Martinsville General District Court",
#     "Mathews Circuit Court",
#     "Mathews General District Court",
#     "Mecklenburg Circuit Court",
#     "Mecklenburg General District Court",
#     "Middlesex Circuit Court",
#     "Middlesex General District Court",
#     "Montgomery Circuit Court",
#     "Nelson Circuit Court",
#     "Nelson General District Court",
#     "New Kent Circuit Court",
#     "New Kent General District Court",
#     "Newport News Circuit Court",
#     "Norfolk Circuit Court",
#     "Norfolk General District Court",
#     "Norfolk General District-Civil Division",
#     "Northampton Circuit Court",
#     "Northampton General District Court",
#     "Northumberland Circuit Court",
#     "Northumberland General District Court",
#     "Nottoway Circuit Court",
#     "Nottoway General District Court",
#     "Orange Circuit Court",
#     "Orange General District Court",
#     "Page Circuit Court",
#     "Page General District Court",
#     "Patrick Circuit Court",
#     "Patrick General District Court",
#     "Petersburg Circuit Court",
#     "Petersburg General District Court",
#     "Pittsylvania Circuit Court",
#     "Pittsylvania General District Court",
#     "Portsmouth Circuit Court",
#     "Portsmouth General District Court",
#     "Powhatan Circuit Court",
#     "Powhatan General District Court",
#     "Prince Edward Circuit Court",
#     "Prince Edward General District Court",
#     "Prince George Circuit Court",
#     "Prince George General District Court",
#     "Prince William Circuit Court",
#     "Prince William General District Court",
#     "Pulaski Circuit Court",
#     "Pulaski General District Court",
#     "Radford Circuit Court",
#     "Radford General District Court",
#     "Rappahannock Circuit Court",
#     "Rappahannock General District Court",
#     "Richmond City Circuit Court",
#     "RICHMOND CITY GENERAL DISTRICT COURT",
#     "Richmond County Circuit Court",
#     "Richmond County General District Court",
#     "Richmond-Civil General District Court",
#     "Roanoke City Circuit Court",
#     "Roanoke City General District Court",
#     "Roanoke County Circuit Court",
#     "Roanoke County General District Court",
#     "Rockbridge Circuit Court",
#     "Rockingham Circuit Court",
#     "Russell Circuit Court",
#     "Russell General District Court",
#     "Salem Circuit Court",
#     "Salem General District Court",
#     "Scott Circuit Court",
#     "Scott General District Court",
#     "Shenandoah Circuit Court",
#     "Shenandoah General District Court",
#     "Smyth Circuit Court",
#     "Smyth General District Court",
#     "Southampton Circuit Court",
#     "Southampton General District Court",
#     "Spotsylvania Circuit Court",
#     "Spotsylvania General District Court",
#     "Stafford Circuit Court",
#     "Stafford General District Court",
#     "Staunton Circuit Court",
#     "Staunton General District Court",
#     "Suffolk Circuit Court",
#     "Suffolk General District Court",
#     "Surry Circuit Court",
#     "Surry General District Court",
#     "Sussex Circuit Court",
#     "Sussex General District Court",
#     "Tazewell Circuit Court",
#     "Tazewell General District Court",
#     "Virginia Beach Circuit Court",
#     "Virginia Beach General District Court",
#     "Warren Circuit Court",
#     "Warren General District Court",
#     "Washington Circuit Court",
#     "Washington General District Court",
#     "Waynesboro Circuit Court",
#     "Waynesboro General District Court",
#     "Westmoreland Circuit Court",
#     "Westmoreland General District Court",
#     "Winchester Circuit Court",
#     "Winchester General District Court",
#     "Wise Circuit Court",
#     "Wise/Norton General District Court",
#     "Wythe Circuit Court",
#     "Wythe General District Court",
#     "York County/Poquoson Circuit Court",
#     "York General District Court",
# ]


# 512-270
# 269-11